### ISSUE TITLE
Member only in one Network

### ISSUE THREAD

**Issue by grallm** [grallm/l2-tasks-project#11]
A Member of only ONE Network, is specific.

Member in multiple Networks could be an upgrade

**Comment by Tomytoo** [comment]
creation d'un attribut inCurrentNetwork de type boolean 
dans la classe member : 
void inNetwork() //negation de inCurrenNetwork
fct utilisé dans la classe network dans l'ajout d'un membre 
si true alors pas possible d'ajouté dans ce network

**Comment by grallm** [comment]
Je pense que c'est utile voire pas une bonne idée, sachant que l'on aura un attribut avec le Network dans lequel il est afin de le connaître il suffit de vérifier que sa valeur ne soit pas "null"
De plus cela fera moins d'attributs

**Comment by grallm** [comment]
Comment fait-on pour Admin ?
L'Admin étend un Member mais si l'on doit donner un network au Member, comme on fait pour Admin ?
